scheduler:
  #_target_: apscheduler.schedulers.background.BackgroundScheduler
  _target_: apscheduler.schedulers.blocking.BlockingScheduler
  jobstores:
    default:
      _target_: apscheduler.jobstores.memory.MemoryJobStore
  executors:
    default:
      _target_: apscheduler.executors.pool.ThreadPoolExecutor
      max_workers: 20
  job_defaults:
    coalesce: false
    max_instances: 1
  timezone:
    _target_: pytz.timezone
    zone: Europe/Berlin
integrations:
  - _target_: src.integrations.heating.heating.HeatingIntegration
    _partial_: true
